
package pkgInterface.Dialogs;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import util.Cliente;

/**
 *
 * @author felip
 */
public class FinalizarVenda extends javax.swing.JPanel {

    private static final int MODO_DINHEIRO = 1;
    private static final int MODO_CARTAO = 2;
    private static final int MODO_A_PRAZO = 3;
    private Cliente cliente = null;
    
    public FinalizarVenda() {
        initComponents();
        modoPag();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgModoDeBusca = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbFormaDePagamento = new javax.swing.JComboBox<>();
        lblValorTotal = new javax.swing.JLabel();
        btnConfirma = new javax.swing.JButton();
        painelCliente = new javax.swing.JPanel();
        edtCodigoDoCliente = new javax.swing.JTextField();
        lblCodCliente = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        edtNomeDoCliente = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de pagamento"));

        cmbFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Dinheiro", "Cartão", "Venda à prazo" }));

        lblValorTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblValorTotal.setText("R$ 120,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValorTotal)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotal))
                .addGap(64, 64, 64))
        );

        btnConfirma.setText("CONFIRMAR");
        btnConfirma.setEnabled(false);
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        painelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        painelCliente.setEnabled(false);

        edtCodigoDoCliente.setEditable(false);
        edtCodigoDoCliente.setEnabled(false);

        lblCodCliente.setText("Código");
        lblCodCliente.setEnabled(false);

        lblNomeCliente.setText("Nome do Cliente");
        lblNomeCliente.setEnabled(false);

        edtNomeDoCliente.setEditable(false);
        edtNomeDoCliente.setEnabled(false);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setEnabled(false);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtCodigoDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelClienteLayout.createSequentialGroup()
                        .addComponent(lblNomeCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(edtNomeDoCliente))
                .addGap(15, 15, 15)
                .addComponent(btnPesquisar)
                .addContainerGap())
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodCliente)
                    .addComponent(lblNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCodigoDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtNomeDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(55, 55, 55))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FINALIZAR VENDA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        buscarCliente();
    }//GEN-LAST:event_btnPesquisarActionPerformed
    
    //Configura o painel de escolha do cliente conforme o modo de pagamento selecionado
    private void modoPag(){
        cmbFormaDePagamento.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(cmbFormaDePagamento.getSelectedIndex() == MODO_A_PRAZO){
                    painelCliente.setEnabled(true);
                    btnPesquisar.setEnabled(true);
                    lblCodCliente.setEnabled(true);
                    lblNomeCliente.setEnabled(true);
                    btnConfirma.setEnabled(false);
                } else if(cmbFormaDePagamento.getSelectedIndex() == MODO_CARTAO || cmbFormaDePagamento.getSelectedIndex() == MODO_DINHEIRO){
                          painelCliente.setEnabled(false);
                          edtCodigoDoCliente.setText("");
                          btnPesquisar.setEnabled(false);
                          edtNomeDoCliente.setText("");
                          btnConfirma.setEnabled(true);
                          lblCodCliente.setEnabled(false);
                          lblNomeCliente.setEnabled(false);
                          cliente = null;
                }
                else {
                    painelCliente.setEnabled(false);
                    edtCodigoDoCliente.setText("");
                    btnPesquisar.setEnabled(false);
                    edtNomeDoCliente.setText("");
                    btnConfirma.setEnabled(true);
                    lblCodCliente.setEnabled(false);
                    lblNomeCliente.setEnabled(false);
                    cliente = null;
                    btnConfirma.setEnabled(false);
                }
                        
            }
        });
    }
    
    private void buscarCliente(){
        DialogPesquisaCliente d = new DialogPesquisaCliente(null);
        d.setLocationRelativeTo(this);
        d.show();
        cliente = d.getClienteSelecionado();
        edtCodigoDoCliente.setText(""+cliente.getCodigo());
        edtCodigoDoCliente.setEnabled(true);
        edtNomeDoCliente.setText(cliente.getNome());
        edtNomeDoCliente.setEnabled(true);
        btnConfirma.setEnabled(true);
    }

    public JButton getBtnConfirma() {
        return btnConfirma;
    }

    public void setBtnConfirma(JButton btnConfirma) {
        this.btnConfirma = btnConfirma;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public JComboBox<String> getCmbFormaDePagamento() {
        return cmbFormaDePagamento;
    }

    public void setCmbFormaDePagamento(JComboBox<String> cmbFormaDePagamento) {
        this.cmbFormaDePagamento = cmbFormaDePagamento;
    }

    public JLabel getLblValorTotal() {
        return lblValorTotal;
    }

    public void setLblValorTotal(JLabel lblValorTotal) {
        this.lblValorTotal = lblValorTotal;
    }
    
    
    
    
    
    
    
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbFormaDePagamento;
    private javax.swing.JTextField edtCodigoDoCliente;
    private javax.swing.JTextField edtNomeDoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel painelCliente;
    private javax.swing.ButtonGroup rgModoDeBusca;
    // End of variables declaration//GEN-END:variables
}
